### ISSUE TITLE
using with StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by sewarts** [Cybermaxs/RedisMemoryCacheInvalidation#1]
I require StackExchange.Redis.StrongName in my project - is there a way to use RedisMemoryCacheInvalidation with StackExchange.Redis.StrongName reference instead of StackExchange.Redis?

**Comment by sewarts** [comment]
I've created my own version swapping out the StackExchange.Redis reference with StackExchange.Redis.StrongName.

**Comment by cybermaxs** [comment]
As you noticed, StackExchange.Redis.StrongName is not currently supported. Strong-naming is a topic that generates a great deal of conflict in the .Net community. I will think about using SN in a future version.

**Comment by sewarts** [comment]
Thanks for response (and RedisMemoryCacheInvalidation). Have swapped in StongName reference and seems to have done the job without hitch.
